# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metaplay < Formula
  desc "CLI tool to manage the Metaplay SDK in game projects, make cloud deployments, and more."
  homepage "https://www.metaplay.io/"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metaplay/cli/releases/download/0.8.0/MetaplayCLI_Darwin_x86_64.tar.gz"
      sha256 "f994f4f38c2d91ffbf33e2d365ebddf029b1fc4e7a02a2dfd7b0259143de2551"

      def install
        bin.install "metaplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metaplay/cli/releases/download/0.8.0/MetaplayCLI_Darwin_arm64.tar.gz"
      sha256 "74fcdb70c257c71a218c1c408278be2ff4df423970b3518fc3511949b38a8f60"

      def install
        bin.install "metaplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metaplay/cli/releases/download/0.8.0/MetaplayCLI_Linux_x86_64.tar.gz"
        sha256 "8cdc42a0d919ce6a1c479d8e77f5b10a2934fb932c740ca4dbf23c9f6555c78d"

        def install
          bin.install "metaplay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metaplay/cli/releases/download/0.8.0/MetaplayCLI_Linux_arm64.tar.gz"
        sha256 "6656a3b73224e449ab1bd9e52e1f4d45112393484c7eaf9815822e1a77e989b8"

        def install
          bin.install "metaplay"
        end
      end
    end
  end

  test do
    system "#{bin}/metaplay version"
  end
end
