# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metaplay < Formula
  desc "CLI tool to manage the Metaplay SDK in game projects, make cloud deployments, and more."
  homepage "https://www.metaplay.io/"
  version "1.8.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metaplay/cli/releases/download/1.8.6/MetaplayCLI_Darwin_x86_64.tar.gz"
      sha256 "1edb12c904e784f2387d09febc9008f467a9970d0be1c1047790a66174b097b2"

      def install
        bin.install "metaplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metaplay/cli/releases/download/1.8.6/MetaplayCLI_Darwin_arm64.tar.gz"
      sha256 "b999262cf21f8f4341d4949c839960df0eb9d04d897ea529ce530a596c2e5cf7"

      def install
        bin.install "metaplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metaplay/cli/releases/download/1.8.6/MetaplayCLI_Linux_x86_64.tar.gz"
      sha256 "0fdea7280f534010ba3cc74d26eeef1f7c7bc2f353ee50a96161867c0ed7acce"
      def install
        bin.install "metaplay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metaplay/cli/releases/download/1.8.6/MetaplayCLI_Linux_arm64.tar.gz"
      sha256 "4152f1ee71f8158592e8a373b9736243d783205dcfa21af786da4d293fbe0df4"
      def install
        bin.install "metaplay"
      end
    end
  end

  test do
    system "#{bin}/metaplay version"
  end
end
